### ISSUE TITLE
Quick overview of an account on the timeline

### ISSUE THREAD

**Issue by Ni-Ti** [VernissageApp/VernissageWeb#105]
A feature that would be interesting to see on Vernissage when browsing a timeline: a quick preview of the account when hovering over the nickname with the description and a follow button to subscribe to the account directly.

Here is a quick mockup that I made of the style of interface that I imagine :

![vernissage](https://github.com/user-attachments/assets/caa050a7-26bd-4f65-99e3-4e40fcca641f)

What do you think? :slightly_smiling_face:

**Comment by kazukyakayashi** [comment]
With less rounding it wouldn't be bad.

**Comment by Ni-Ti** [comment]
![vernissage_2](https://github.com/user-attachments/assets/7c0ab394-cf50-41b3-bcf2-cb0322afe795)

**Comment by mczachurski** [comment]
This is a very good idea!
