### ISSUE TITLE
Timeline scroll position is not preserved after navigating to a post and returning

### ISSUE THREAD

**Issue by mgrzeca** [VernissageApp/VernissageWeb#127]
When scrolling down the timeline and then clicking on a post to view or comment on it, upon returning to the timeline, the scroll position resets to near the top of the page. The previous scroll position is not preserved.

It seems like there might be a missing scrollPositionRestoration option in the route configuration. Implementing this would greatly improve the user experience by allowing users to continue from where they left off in the timeline after interacting with a post.

**Comment by mczachurski** [comment]
I think I manage to figure out solution also for user's profile.
