### ISSUE TITLE
Content Warning Effects and Avatar Missing on Shared Statuses in Timeline

### ISSUE THREAD

**Issue by mgrzeca** [VernissageApp/VernissageWeb#149]
Shared statuses with a content warning are visible on the timeline without any of the effects typically associated with content warnings, such as the blur effect. Additionally, the avatar is missing for these shared statuses.

See, for example, the status with the nude male figure on the right side:

<img width="1552" alt="Zrzut ekranu 2024-11-6 o 21 20 24" src="https://github.com/user-attachments/assets/e22218ab-d209-4455-a7ee-c5b3fb48cfd0">
<img width="1552" alt="Zrzut ekranu 2024-11-6 o 21 20 32" src="https://github.com/user-attachments/assets/d266d8f9-1f59-41cb-96a8-a6890a93237f">

**Comment by mczachurski** [comment]
I verified that issue, and on my timeline I have image blurred. Maybe you have that settings on:

<img width="680" alt="Screenshot 2024-11-07 at 07 11 38" src="https://github.com/user-attachments/assets/237ef329-3669-4c35-bd8a-5165540fef10">

If yes, then the bug is on the status details 😉.

**Comment by mczachurski** [comment]
Currently, the sensitive content warning will not be displayed anywhere (including on the status details) if the user has set this option.
