### ISSUE TITLE
Three-column Masonry grid breaks under certain statuses.

### ISSUE THREAD

**Issue by mgrzeca** [VernissageApp/VernissageWeb#24]
It looks like in the attached screenshot - one of the columns loads only partially.
Below are links to the statuses causing this issue:

https://grzeca.eu/statuses/7357822278527717377
https://grzeca.eu/statuses/7358859203891212289

<img width="1440" alt="Zrzut ekranu 2024-04-18 o 15 39 49" src="https://github.com/VernissageApp/VernissageWeb/assets/2249297/298d8eea-74be-46a7-9aef-c9099dee9359">

**Comment by mczachurski** [comment]
Seems like these statuses shouldn't be visible on timeline. These statuses don't contain any images.

Generally it seems like `EZLorenzImagery@socel.net` first added a status with image, then added comment to that status (without image). Both statuses have been downloaded to database (original and comment). And then `EZLorenzImagery@socel.net`  boosted the comment, which has been unfortunately added to the timeline.

**Comment by mczachurski** [comment]
Fix on server side. Unfortunately you have to delete these statuses manually (from status details page).
Thanks a lot for reporting this bug, I wouldn't have found it in my life 🤣.
